#!/bin/bash

code --install-extension austenc.laravel-blade-spacer
code --install-extension bmewburn.vscode-intelephense-client
code --install-extension calebporzio.better-phpunit
code --install-extension christian-kohler.npm-intellisense
code --install-extension DavidAnson.vscode-markdownlint
code --install-extension dbaeumer.vscode-eslint
code --install-extension DotJoshJohnson.xml
code --install-extension eamodio.gitlens
code --install-extension EditorConfig.EditorConfig
code --install-extension eg2.tslint
code --install-extension emmanuelbeziat.vscode-great-icons
code --install-extension esbenp.prettier-vscode
code --install-extension felixfbecker.php-debug
code --install-extension felixfbecker.php-intellisense
code --install-extension formulahendry.code-runner
code --install-extension heberalmeida.php-snippets
code --install-extension ikappas.composer
code --install-extension junstyle.php-cs-fixer
code --install-extension msjsdiag.debugger-for-chrome
code --install-extension nikitaKunevich.snippet-creator
code --install-extension octref.vetur
code --install-extension onecentlin.laravel-blade
code --install-extension onecentlin.laravel-extension-pack
code --install-extension onecentlin.laravel5-snippets
code --install-extension ryannaddy.laravel-artisan
code --install-extension santigarcor.phpunit-extended
code --install-extension shardulm94.trailing-spaces
code --install-extension sleistner.vscode-fileutils
code --install-extension techer.open-in-browser
code --install-extension wayou.vscode-todo-highlight
code --install-extension whizkydee.material-palenight-theme
code --install-extension wix.vscode-import-cost
code --install-extension xyz.local-history
